(load "~/.emacs.d/moduals/lsp/eglot.el")
(load "~/.emacs.d/moduals/lsp/eglot-hooks.el")
(load "~/.emacs.d/moduals/lsp/html.el")
(load "~/.emacs.d/moduals/lsp/lua.el")
(load "~/.emacs.d/moduals/lsp/nix.el")
(load "~/.emacs.d/moduals/lsp/go.el")
(load "~/.emacs.d/moduals/lsp/harper.el")
(load "~/.emacs.d/moduals/lsp/treesit.el")
(load "~/.emacs.d/moduals/lsp/typst.el")
;; (load "~/.emacs.d/moduals/lsp/latex.el")
;; (load "~/.emacs.d/moduals/lsp/lsp-bridge.el")
