;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-visual-line
        dired-toggle-read-only
        end-of-visual-line
        help-customize
        help-goto-info
        keycast-mode-line-mode
        my/backward-kill-spaces-or-char-or-word
        rectangle-number-lines
        undefined
        wdired--self-insert
        wdired-finish-edit
        ))

(setq mc/cmds-to-run-once
      '(
        text-scale-adjust
        ))
